name: 16 - Working with Environments
#run-name: 16 - Working with Environments | env - ${{ github.events.inputs.target-env }}
on:
   workflow_dispatch:
     inputs:
       target-env:
         type: environment
         default: staging
jobs:
 #echo:
 deploy-staging:
   runs-on: ubuntu-latest
   environment: staging #${{ github.events.inputs.target-env }}
   env:
     my-env-value: ${{ vars.MY_ENV_VALUE || 'default value'}}
   steps: 
     - name: Echo vars
       run: echo Deploying to staging #echo "Env variable ${{ env.my-env-value }}"
 e2e-tests:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
       - name: E2E tests
         run: echo Running E2E
 deploy-prod:
   runs-on: ubuntu-latest
   needs: e2e-tests
   environment: prod
   env: 
      my-env-value: ${{ vars.MY_ENV_VALUE || 'default value' }}
   steps:
      - name: Echo vars
        run: echo Deploying to prod
   
