name: 17 - 2 - Custom Actions - JS
run-name: 17 - 2 - Custom Actions - JS | ${{ inputs.base-branch }}-${{ inputs.target-branch }}-${{ inputs.working-dir }}

on: 
  workflow_dispatch:
    #inputs:
      #base-branch:
        #description: The branch used as the base for the dependency update checks
        #default: main
        #required: false
      #target-branch:
        #description: description of The branch from which the PR is created
        #default: default of update-dependencies
        #required: false
      #working-directory:
        #description: The working directory of the project to check for dependency updates
        #required: true
      #debug:
        #description: Whether the output debug messages to the console
        #required: false

permissions:
  contents: write
  pull-requests: write
jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check for dependency updates
      uses: ./.github/actions/js-dependency-update
      with: 
        base-branch: main
        target-branch: update-dependencies
        working-directory: 17-custom-actions/react-app
        debug: false
        gh-token: ${{ secrets.GITHUB_TOKEN }}

  
